name: rough
description: Rough is a library that allows you draw in a sketchy, hand-drawn-like style
version: 0.1.0+2
homepage: https://github.com/sergiandreplace/flutter_rough
repository: https://github.com/sergiandreplace/flutter_rough

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
